### ISSUE TITLE
How many boars/sensors possible?!

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_Python_MAX31855#1]
Hello Tony,

Thanks for your work, just got the https://learn.adafruit.com/max31855-thermocouple-python-library/software working!

Just changed the max31855K for the J, since my sensor is J type, all working like a charm.
(Had to reverse red/yellow, since more heat would make temperature lower :) )

I have python reading the temp (software SPI), that invokes php on a subproc, that fires a laravel command, saving to a cloud mysql and also saves locally on a csv. sweet!

What i'm thinking is, how many sensors/breakout boards can i have working simultaneously?

Can i share any pins, and get use of the free pins on the RPi ?

**Comment by tdicola** [comment]
Awesome, I'm glad the library works well for you--thanks for checking it out!  Since the chip uses SPI you can connect quite a few of them to a Raspberry Pi and read each one individually.  All of the chips will need to share the same clock and data out lines (in the simpletest.py example those are lines 25 and 18 respectively).  However each chip will need a unique CS / chip select pin (pin 24 in the example).  You can use any digital GPIO pin as a CS pin, so really you're just limited by the number of free digital GPIO pins on the Pi--which is a lot on the Pi 2 (over 20).  Thanks again for checking out the library!

**Comment by ghost** [comment]
Nice timing! Hmm that's good news.

If seeking over 20 devices, is it possible to read with arduino, and transmitting to RPi ?

Strange with your library is i get a lot of NAN values...
I even made a own function to read temp only if is not NAN until 200 times, but got NAN anyway!
It alternates between the correct value and nan.
Do you have any idea what can be going wrong?

![image](https://cloud.githubusercontent.com/assets/6516477/10303148/8e6a348a-6c09-11e5-81f3-0c9a68380503.png)

![image](https://cloud.githubusercontent.com/assets/6516477/10303229/fea53d9e-6c09-11e5-8874-30f4086978dc.png)

**Comment by ghost** [comment]
Sorry, i realised the graph was different timestamps...
with that function readTemperature() i dont get nans, but wondering what can be going on!

**Comment by tdicola** [comment]
Ah interesting, the library will return a NaN result if the chip tells it there was an error or fault making the reading (can see the logic here: https://github.com/adafruit/Adafruit_Python_MAX31855/blob/master/Adafruit_MAX31855/MAX31855.py#L98).  From the datasheet (see: https://www.adafruit.com/datasheets/MAX31855.pdf) it looks like these conditions can flip the error / fault bit for a reading:

```
D2 SCV Fault This bit is a 1 when the thermocouple is short-circuited to VCC. Default value is 0.
D1 SCG Fault This bit is a 1 when the thermocouple is short-circuited to GND. Default value is 0.
D0 OC Fault This bit is a 1 when the thermocouple is open (no connections). Default value is 0
```

You might double check the thermocouple isn't shorting to VCC, gnd, or disconnecting as that would cause the fault bit to turn on and a NaN result to be returned.

**Comment by ghost** [comment]
Thanks i will check it. Nevertheless, that function developed readTemperature() fixed the readings, all is going great!
Thank you for your time and support!! Great work!!
