### ISSUE TITLE
readLinearizedTempC() correction

### ISSUE THREAD

**Issue by nightmechanic** [adafruit/Adafruit_Python_MAX31855#5]
Hi,
I think there is a mistake in the readLinearizedTempC(),
in lines 122, 133 and 144:

the conditions (voltage level) should be checked on the "voltageSum" variable and not on the "thermocoupleVoltage" variable.

This error causes erroneous temperature results (and a large temperature "jump") when the external temperature is close to the internal ("cold junction") one.

in: https://learn.adafruit.com/calibrating-sensors/maxim-31855-linearization, you can see that in the code from 'heypete' it is implemented correctly (vs. the code from 'jh421797') according to the text (from Maxim Integrated) in: https://forums.adafruit.com/viewtopic.php?f=19&t=32086&start=15#p372992

This is, of course, reproducible on any platform.

**Comment by tgikal** [comment]
Edited file with corrected calculations and "NaN" error added to readLinearizedTempC().
Just in case anybody actually wants a working module.

Opened a Pull Request with a fix [https://github.com/adafruit/Adafruit_Python_MAX31855/pull/7](https://github.com/adafruit/Adafruit_Python_MAX31855/pull/7)

**Comment by ladyada** [comment]
hiya this library is being deprecated, and replaced with our shiny new circuitpython library, which has this function ported over
we are archiving this repo
please check out https://github.com/adafruit/Adafruit_CircuitPython_MAX31855/
and if it is still amiss please open an issue in that repo!
