### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by milkriel** [adafruit/Adafruit_Python_MAX31855#6]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
Beaglebone with Debian

- Python version (run `python -version` or `python3 -version`):  
Python 2.7.3
- Error message you are receiving, including any Python exception traces: 
root@beaglebone:~/Adafruit_Python_MAX31855-master# sudo python setup.py install
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-3.5.                                                                                                             1.zip
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    use_setuptools()
  File "/root/Adafruit_Python_MAX31855-master/ez_setup.py", line 149, in use_set                                                                                                             uptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/root/Adafruit_Python_MAX31855-master/ez_setup.py", line 107, in _do_dow                                                                                                             nload
    to_dir, download_delay)
  File "/root/Adafruit_Python_MAX31855-master/ez_setup.py", line 287, in downloa                                                                                                             d_setuptools
    downloader(url, saveto)
  File "/root/Adafruit_Python_MAX31855-master/ez_setup.py", line 194, in downloa                                                                                                             d_file_curl
    _clean_check(cmd, target)
  File "/root/Adafruit_Python_MAX31855-master/ez_setup.py", line 157, in _clean_                                                                                                             check
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://pypi.python.org/packag                                                                                                             es/source/s/setuptools/setuptools-3.5.1.zip', '--silent', '--output', '/root/Ada                                                                                                             fruit_Python_MAX31855-master/setuptools-3.5.1.zip']' returned non-zero exit stat                                                                                                             us 60

**Comment by michaelbironneau** [comment]
I'm also getting issues with same system as the above poster and the following error message:

```
[main]   ---> Running in 3be1d6f61cb6
[main]  Cloning into 'Adafruit_Python_MAX31855'...
[main]  
[main]  Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-3.5.1.zip
[main]  
[main]  Extracting in /tmp/tmpm2jGQK
[main]  
[main]  Traceback (most recent call last):
[main]    File "setup.py", line 4, in <module>
[main]      use_setuptools()
[main]    File "/usr/src/app/Adafruit_Python_MAX31855/ez_setup.py", line 128, in use_setuptools
[main]      return _do_download(version, download_base, to_dir, download_delay)
[main]    File "/usr/src/app/Adafruit_Python_MAX31855/ez_setup.py", line 108, in _do_download
[main]      _build_egg(egg, archive, to_dir)
[main]    File "/usr/src/app/Adafruit_Python_MAX31855/ez_setup.py", line 57, in _build_egg
[main]      with archive_context(archive_filename):
[main]    File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
[main]      return self.gen.next()
[main]    File "/usr/src/app/Adafruit_Python_MAX31855/ez_setup.py", line 88, in archive_context
[main]      with get_zip_class()(filename) as archive:
[main]  
[main]    File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
[main]  
[main]      self._RealGetContents()
[main]    File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
[main]  
[main]      raise BadZipfile, "File is not a zip file"
[main]  zipfile.BadZipfile: File is not a zip file
[main]  
[main]  Removing intermediate container 3be1d6f61cb6
[main]  The command '/bin/sh -c git clone https://github.com/adafruit/Adafruit_Python_MAX31855.git && 	cd Adafruit_Python_MAX31855 && 	sudo python setup.py install && 	cd ..' returned a non-zero code: 1

```

**Comment by ladyada** [comment]
hiya we're deprecating this library and will be supporing this chip via our CircuitPython library which is also on pypi and is waaay easier to install
https://learn.adafruit.com/thermocouple/python-circuitpython
thanks!
